### ISSUE TITLE
Add eventFilter endpoint from Asterisk 16.3

### ISSUE THREAD

**Issue by lucasvs** [chadxz/awry#110]
https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Applications+REST+API#Asterisk16ApplicationsRESTAPI-filter

**Comment by chadxz** [comment]
happy to accept a pr to add this.

**Comment by chadxz** [comment]
Published in v7.2.0

**Comment by chadxz** [comment]
Thanks for the feature request @lucasvs !
