### ISSUE TITLE
Link to API documentation is invalid

### ISSUE THREAD

**Issue by octoquad** [chadxz/awry#137]
Hi,

The link for the API documentation found in the README is invalid.

> For more details see the full API documentation.

The link points to http://chadmcelligott.com/awry but gets redirected to http://ww25.chadmcelligott.com/awry?subid1=20210830-1605-3571-9af1-060a513179f8. 

Can the URL be updated for the documentation?

**Comment by chadxz** [comment]
Yes, sorry about that. I let that domain name expire and forgot to move the docs elsewhere. 

In the meantime, if you clone the repository and run npm install followed by npm run docs, you can view the docs locally.

**Comment by octoquad** [comment]
Thanks. I've created a PR to get that updated. Feel free to merge or close if you have other plans regarding publishing of the documentation.
